CREATE DATABASE mysql_async_tests;
USE mysql_async_tests;
CREATE TABLE mysql_async_tests.transaction_test (id VARCHAR(255) NOT NULL, PRIMARY KEY (id));
CREATE USER 'mysql_async'@'localhost' IDENTIFIED BY 'root';
CREATE USER 'mysql_async_old'@'localhost';
CREATE USER 'mysql_async_nopw'@'localhost';
GRANT ALL PRIVILEGES ON *.* TO 'mysql_async'@'localhost';
GRANT ALL PRIVILEGES ON *.* TO 'mysql_async_old'@'localhost';
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'mysql_async_nopw'@'localhost';
