name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PGUSER: postgres
      MYSQLV: '5.7'
      PGV: '10'
    strategy:
     matrix:
       scala: [2.11.12, 2.12.18, 2.13.12, 3.3.1]
    timeout-minutes: 10
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Start postgresql & mysql
        working-directory: build/server
        run:
          docker-compose up -d && docker-compose logs
      - name: Setup database
        run: bash build/prepare_build.sh


      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
            ~/.cache/coursier
          key: sbt-cache-${{ runner.os }}-${{matrix.scala}}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}

      - name: Tests
        run: sbt ++${{matrix.scala}} test
        if: ${{ !startsWith(matrix.scala, '2.13') }}

      - name: Tests with Coverage
        run: sbt ++${{matrix.scala}} coverage test coverageAggregate
        if: ${{ startsWith(matrix.scala, '2.13') }}

      - name: Upload codecov
        if: ${{ startsWith(matrix.scala, '2.13') }}
        uses: codecov/codecov-action@v1
